# Generated by Django 2.0.7 on 2018-08-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail',
            field=models.CharField(default='', max_length=100, verbose_name='주소를 입력하세요'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='계좌번호와 희망 요금을 입력하세요'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='주소를 입력하세요'),
        ),
    ]
